name: Build domains
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "spotify=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list" >> $GITHUB_ENV
          echo "microsoft1=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list" >> $GITHUB_ENV
          echo "microsoft2=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list" >> $GITHUB_ENV
          echo "apple=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list" >> $GITHUB_ENV
          echo "google=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list" >> $GITHUB_ENV
          echo "telegram=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list" >> $GITHUB_ENV
          echo "china_media=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list" >> $GITHUB_ENV
          echo "foreign_media1=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list" >> $GITHUB_ENV
          echo "foreign_media2=https://raw.githubusercontent.com/izumiChan16/clash_reg/master/rule/pikpak.list" >> $GITHUB_ENV
          echo "emby=https://raw.githubusercontent.com/izumiChan16/clash_reg/master/rule/emby.list" >> $GITHUB_ENV
          echo "vpsdirect=https://raw.githubusercontent.com/izumiChan16/clash_reg/master/rule/vpsdirect.list" >> $GITHUB_ENV
          
        shell: bash

      - name: Checkout codebase
        uses: actions/checkout@master

      - name: Generate Spotify
        run: |
          curl -sSL ${spotify} | grep -Ev '#|IP-' | sort --ignore-case > ./domains/spotify.list

      - name: Generate Microsoft
        run: |
          curl -sSL ${microsoft1} | grep -Ev '#|IP-' > ./tmp/temp-microsoft.txt
          curl -sSL ${microsoft2} | grep -Ev '#|IP-' >> ./tmp/temp-microsoft.txt
          sort --ignore-case -u ./tmp/temp-microsoft.txt > ./domains/microsoft.list

      - name: Generate Apple
        run: |
          curl -sSL ${apple} | grep -Ev '#|IP-' | sort --ignore-case > ./domains/apple.list

      - name: Generate Google
        run: |
          curl -sSL ${google} | grep -Ev '#|IP-' | sort --ignore-case > ./domains/google.list

      - name: Generate Telegram
        run: |
          curl -sSL ${telegram} | grep -Ev '#|IP-' | sort --ignore-case > ./domains/telegram.list

      - name: Generate China Media
        run: |
          curl -sSL ${china_media} | grep -Ev '#|IP-' | sort --ignore-case > ./domains/china_media.list

      - name: Generate Foreign Media
        run: |
          curl -sSL ${foreign_media1} | grep -Ev '#|IP-' > ./tmp/temp-foreign-media.txt
          curl -sSL ${foreign_media2} | grep -Ev '#|IP-' >> ./tmp/temp-foreign-media.txt
          sort --ignore-case -u ./tmp/temp-foreign-media.txt > ./domains/foreign_media.list

      - name: Generate Emby
        run: |
          curl -sSL ${emby} | grep -Ev '#|IP-' | sort --ignore-case > ./domains/emby.list

      - name: Generate vpsdirect
        run: |
          curl -sSL ${vpsdirect} | grep -Ev '#|IP-' | sort --ignore-case > ./domains/vpsdirect.list

      - name: Release and upload `clash` assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: domains
          tag: domains
          overwrite: true
          body: "域名列表文件"
          file_glob: true
          file: ./domains/*

      - name: Git push assets to `domains` branch
        run: |
          cd ./domains/ || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b domains
          git add . && git commit -m "域名列表更新于 $(date -d '+8 hours' +%Y-%m-%d)"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin domains

      - name: Purge jsDelivr CDN
        run: |
          cd ./domains/ || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@domains/${file}"
          done
